WIP: Add ADR for data schema
alphagov/data-standards-authority pull request #112
Opened 2021-11-10 11:23 UTC by jamietanna

2021-11-10 14:51 UTC, charlesbaird-dsa reviewed
As discussed.

2021-11-10 14:51 UTC, charlesbaird-dsa commented on adr/0001-standards-catalogue-data-structure.md
> +As part of plans to enhance the Workbench by produce schema.org metadata, we discovered that the underlying data wasn't quite standardised.
```suggestion
As part of plans to enhance the Workbench by introducing schema.org metadata, we discovered that the underlying data wasn't quite standardised.
```

2021-11-10 15:52 UTC, charlesbaird-dsa approved these changes
Ah nice, you caught the mention of 'catalogue' I missed. Intentional, obvs...

2021-11-10 16:11 UTC, charlesbaird-dsa approved these changes
Sorry, I got bothered by a comma. Other than that lgtm.

2021-11-10 16:11 UTC, charlesbaird-dsa commented on adr/0001-standards-catalogue-data-structure.md
> +The standards section of the Data Standards Authority Workbench (DSA Workbench), is used to capture standards that the DSA are looking at, before they become official guidance on Gov.UK. It is also a
```suggestion
The standards section of the Data Standards Authority Workbench (DSA Workbench) is used to capture standards that the DSA are reviewing, before they become official guidance on Gov.UK. It is also an attempt to map other standards in use across government, both for the DSA's internal prioritisation activities and to enable external users to find relevant data standards. To begin with, this second focus is served by curating a list of standards catalogues.
```

2021-11-10 16:35 UTC, jamietanna commented on adr/0001-standards-catalogue-data-structure.md
> +TBC
needs addressing

2021-11-10 16:35 UTC, arnau requested changes

2021-11-10 16:35 UTC, arnau commented on adr/0001-standards-catalogue-data-structure.md
> +```
Tweaked the ERD to express the relationship betwen Standard - Event - Status:

```suggestion
[Standard]
*identifier
name { label: "string, required" }
contraction { label: "string, required" }
specification_url { label: "url, required" }
description { label: "markdown" }
+topic_id
+licence_id
+maintainer_id

[Event]
+standard_id
+status_id
date {label: "required, date"}

[Status]
*identifier
name
description

[Tag]
*identifier
name
description

[Licence]
*identifier {label: "string, required"}
name {label: "string, required"}
type {label: "enum[OPEN,PROPRIETARY,UNKNOWN]"}
url {label: "url"}

[Organisation]
*identifier
name {label: "string, required"}
url {label: "url, required"}

Standard 1--* Standard
Standard 1--+ Tag
Standard 1--1 Licence
Standard 1--1 Organisation
Standard 1--+ Event
Event 1--1 Status
```

2021-11-11 10:12 UTC, arnau approved these changes
Nice one! 🚢

2021-11-11 10:18 UTC, merged